name: polartoolkit
channels:
  - conda-forge
dependencies:
  - _libavif_api=1.1.1=h57928b3_2
  - _openmp_mutex=4.5=2_gnu
  - affine=2.4.0=pyhd8ed1ab_1
  - aiobotocore=2.15.2=pyhd8ed1ab_0
  - aiohappyeyeballs=2.4.4=pyhd8ed1ab_1
  - aiohttp=3.11.11=py312h31fea79_0
  - aioitertools=0.12.0=pyhd8ed1ab_0
  - aiosignal=1.3.2=pyhd8ed1ab_0
  - aom=3.9.1=he0c23c2_0
  - asciitree=0.3.3=py_2
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=24.3.0=pyh71513ae_0
  - aws-c-auth=0.8.0=h2219d47_15
  - aws-c-cal=0.8.1=h099ea23_3
  - aws-c-common=0.10.6=h2466b09_0
  - aws-c-compression=0.3.0=h099ea23_5
  - aws-c-event-stream=0.5.0=h85d8506_11
  - aws-c-http=0.9.2=h3888f84_4
  - aws-c-io=0.15.3=hc5a9e45_5
  - aws-c-mqtt=0.11.0=h2c94728_12
  - aws-c-s3=0.7.7=h6a38c86_0
  - aws-c-sdkutils=0.2.1=h099ea23_4
  - aws-checksums=0.2.2=h099ea23_4
  - aws-crt-cpp=0.29.7=h0642867_7
  - aws-sdk-cpp=1.11.458=h5f5f9c4_4
  - blosc=1.21.6=hfd34d9b_1
  - bokeh=3.6.2=pyhd8ed1ab_1
  - botocore=1.35.36=pyge310_1234567_0
  - bounded-pool-executor=0.0.3=pyhd8ed1ab_0
  - branca=0.8.1=pyhd8ed1ab_0
  - brotli=1.1.0=h2466b09_2
  - brotli-bin=1.1.0=h2466b09_2
  - brotli-python=1.1.0=py312h275cf98_2
  - bzip2=1.0.8=h2466b09_7
  - c-ares=1.34.4=h2466b09_0
  - ca-certificates=2024.12.14=h56e8100_0
  - certifi=2024.12.14=pyhd8ed1ab_0
  - cffi=1.17.1=py312h4389bb4_0
  - cftime=1.6.4=py312h1a27103_1
  - charset-normalizer=3.4.0=pyhd8ed1ab_1
  - choclo=0.3.1=pyhd8ed1ab_0
  - click=8.1.7=win_pyh7428d3b_1
  - click-plugins=1.1.1=pyhd8ed1ab_1
  - cligj=0.7.2=pyhd8ed1ab_2
  - cloudpickle=3.1.0=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.1=py312hd5eb7cc_0
  - coverage=7.6.9=py312h31fea79_0
  - cpython=3.12.8=py312hd8ed1ab_1
  - curl=8.11.1=h88aaa65_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cytoolz=1.0.1=py312h4389bb4_0
  - dask=2024.12.1=pyhd8ed1ab_0
  - dask-core=2024.12.1=pyhd8ed1ab_0
  - dask-expr=1.1.21=pyhd8ed1ab_0
  - dav1d=1.2.1=hcfcfb64_0
  - debugpy=1.8.11=py312h275cf98_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - deepdiff=8.1.1=pyhd8ed1ab_0
  - deprecation=2.1.0=pyh9f0ad1d_0
  - distributed=2024.12.1=pyhd8ed1ab_0
  - docrep=0.3.2=pyh44b312d_0
  - earthaccess=0.12.0=pyhd8ed1ab_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - fasteners=0.17.3=pyhd8ed1ab_0
  - fftw=3.3.10=nompi_h89e6982_110
  - fiona=1.10.1=py312h6e88f47_3
  - folium=0.19.2=pyhd8ed1ab_0
  - fonttools=4.55.3=py312h31fea79_0
  - freetype=2.12.1=hdaf720e_2
  - freexl=2.0.0=hf297d47_2
  - frozenlist=1.5.0=py312h4389bb4_0
  - fsspec=2024.10.0=pyhd8ed1ab_1
  - future=1.0.0=pyhd8ed1ab_1
  - gdal=3.10.0=py312h7a712b6_9
  - geopandas=0.14.4=pyhd8ed1ab_0
  - geopandas-base=0.14.4=pyha770c72_0
  - geos=3.13.0=h5a68840_0
  - geotiff=1.7.3=h496ac4d_3
  - ghostscript=10.04.0=he0c23c2_0
  - gmt=6.5.0=hd52d0d1_7
  - h2=4.1.0=pyhd8ed1ab_1
  - harmonica=0.7.0=pyhd8ed1ab_0
  - hdf4=4.2.15=h5557f11_7
  - hdf5=1.14.3=nompi_hd5d9e70_108
  - hpack=4.0.0=pyhd8ed1ab_1
  - hyperframe=6.0.1=pyhd8ed1ab_1
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.5.0=pyha770c72_1
  - importlib-resources=6.4.5=pyhd8ed1ab_1
  - importlib_resources=6.4.5=pyhd8ed1ab_1
  - iniconfig=2.0.0=pyhd8ed1ab_1
  - intel-openmp=2024.2.1=h57928b3_1083
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.30.0=pyh7428d3b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.4=pyhd8ed1ab_1
  - jmespath=1.0.1=pyhd8ed1ab_1
  - joblib=1.4.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh5737063_1
  - kiwisolver=1.4.7=py312hd5eb7cc_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.16=h67d730c_0
  - lerc=4.0.0=h63175ca_0
  - libabseil=20240722.0=cxx17_he0c23c2_1
  - libaec=1.1.3=h63175ca_0
  - libarchive=3.7.7=h979ed78_3
  - libarrow=18.1.0=h5d48cc5_6_cpu
  - libarrow-acero=18.1.0=h7d8d6a5_6_cpu
  - libarrow-dataset=18.1.0=h7d8d6a5_6_cpu
  - libarrow-substrait=18.1.0=h7c2144a_6_cpu
  - libavif16=1.1.1=h4d049a7_2
  - libblas=3.9.0=26_win64_mkl
  - libbrotlicommon=1.1.0=h2466b09_2
  - libbrotlidec=1.1.0=h2466b09_2
  - libbrotlienc=1.1.0=h2466b09_2
  - libcblas=3.9.0=26_win64_mkl
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.11.1=h88aaa65_0
  - libde265=1.0.15=h91493d7_0
  - libdeflate=1.23=h9062f6e_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.6.4=he0c23c2_0
  - libffi=3.4.2=h8ffe710_5
  - libgcc=14.2.0=h1383e82_1
  - libgdal-core=3.10.0=hc01691a_9
  - libgdal-jp2openjpeg=3.10.0=h49009cd_9
  - libglib=2.82.2=h7025463_0
  - libgomp=14.2.0=h1383e82_1
  - libgoogle-cloud=2.32.0=h07d40e7_0
  - libgoogle-cloud-storage=2.32.0=he5eb982_0
  - libgrpc=1.67.1=h7aa3b8a_0
  - libheif=1.18.2=gpl_hc631cee_100
  - libhwloc=2.11.2=default_ha69328c_1001
  - libiconv=1.17=hcfcfb64_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.0.0=hcfcfb64_1
  - libkml=1.3.0=h538826c_1021
  - liblapack=3.9.0=26_win64_mkl
  - liblzma=5.6.3=h2466b09_1
  - libnetcdf=4.9.2=nompi_h008f77d_116
  - libparquet=18.1.0=ha850022_6_cpu
  - libpng=1.6.44=h3ca93ac_0
  - libprotobuf=5.28.2=hcaed137_0
  - libre2-11=2024.07.02=h4eb7d71_1
  - librttopo=1.1.0=hd4c2148_17
  - libsodium=1.0.20=hc70643c_0
  - libspatialindex=2.0.0=h5a68840_0
  - libspatialite=5.1.0=h939089a_12
  - libsqlite=3.47.2=h67fdade_0
  - libssh2=1.11.1=he619c9f_0
  - libthrift=0.21.0=hbe90ef8_0
  - libtiff=4.7.0=h797046b_3
  - libutf8proc=2.9.0=h2466b09_1
  - libwebp-base=1.4.0=hcfcfb64_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_8
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.5=he286e8c_1
  - libzip=1.11.2=h3135430_0
  - libzlib=1.3.1=h2466b09_2
  - llvmlite=0.43.0=py312h1f7db74_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.3=py312h032eceb_2
  - lz4-c=1.10.0=h2466b09_1
  - lzo=2.10=hcfcfb64_1001
  - mapclassify=2.8.1=pyhd8ed1ab_1
  - markupsafe=3.0.2=py312h31fea79_1
  - matplotlib-base=3.10.0=py312h90004f6_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - minizip=4.0.7=h9fa1bad_3
  - mkl=2024.2.2=h66d3029_15
  - msgpack-python=1.1.0=py312hd5eb7cc_0
  - multidict=6.1.0=py312h31fea79_1
  - multimethod=1.12=pyhd8ed1ab_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - netcdf4=1.7.2=nompi_py312h39e0dc6_101
  - networkx=3.4.2=pyh267e887_2
  - numba=0.60.0=py312hcccf92d_0
  - numcodecs=0.13.1=py312h72972c8_0
  - numpy=2.0.2=py312h49bc9c5_1
  - openjpeg=2.5.3=h4d64b90_0
  - openpyxl=3.1.5=py312he70551f_1
  - openssl=3.4.0=h2466b09_0
  - orc=2.0.3=h303113e_1
  - orderly-set=5.2.3=pyh29332c3_1
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py312h72972c8_1
  - parso=0.8.4=pyhd8ed1ab_1
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre=8.45=h0e60522_0
  - pcre2=10.44=h3d7b363_2
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.0.0=py312ha41cd45_0
  - pip=24.3.1=pyh8b19718_2
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - pluggy=1.5.0=pyhd8ed1ab_1
  - polartoolkit=0.7.1=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_1
  - pqdm=0.2.0=pyhd8ed1ab_0
  - proj=9.5.1=h4f671f6_0
  - proj-data=1.20=h7428d3b_0
  - prompt-toolkit=3.0.48=pyha770c72_1
  - propcache=0.2.1=py312h4389bb4_0
  - psutil=6.1.0=py312h4389bb4_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=18.1.0=py312h2e8e312_0
  - pyarrow-core=18.1.0=py312h6a9c419_0_cpu
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.18.0=pyhd8ed1ab_1
  - pygmt=0.13.0=pyhd8ed1ab_0
  - pyparsing=3.2.0=pyhd8ed1ab_2
  - pysocks=1.7.1=pyh09c184e_7
  - pytest=8.3.4=pyhd8ed1ab_1
  - pytest-cov=6.0.0=pyhd8ed1ab_1
  - python=3.12.8=h3f84c4b_1_cpython
  - python-cmr=0.13.0=pyhd8ed1ab_0
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-dotenv=1.0.1=pyhd8ed1ab_1
  - python-tzdata=2024.2=pyhd8ed1ab_1
  - python_abi=3.12=5_cp312
  - pytz=2024.1=pyhd8ed1ab_0
  - pywin32=307=py312h275cf98_3
  - pyyaml=6.0.2=py312h4389bb4_1
  - pyzmq=26.2.0=py312hd7027bb_3
  - qhull=2020.2=hc790b64_5
  - rasterio=1.4.3=py312hc0daee4_0
  - rav1e=0.6.6=h975169c_2
  - re2=2024.07.02=hd3b24a8_1
  - requests=2.32.3=pyhd8ed1ab_1
  - rioxarray=0.17.0=pyhd8ed1ab_0
  - rtree=1.3.0=py312h9e53377_2
  - s3fs=2024.10.0=pyhd8ed1ab_1
  - scikit-learn=1.6.0=py312h816cc57_0
  - scipy=1.14.1=py312h337df96_2
  - setuptools=75.6.0=pyhff2d567_1
  - shapely=2.0.6=py312h0c580ee_2
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h500f7fa_1
  - snuggs=1.4.7=pyhd8ed1ab_2
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - sqlite=3.47.2=h2466b09_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - svt-av1=2.3.0=he0c23c2_0
  - tbb=2021.13.0=h62715c5_1
  - tblib=3.0.0=pyhd8ed1ab_1
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tinynetrc=1.3.1=pyhd8ed1ab_0
  - tk=8.6.13=h5226925_1
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - toolz=1.0.0=pyhd8ed1ab_1
  - tornado=6.4.2=py312h4389bb4_0
  - tqdm=4.67.1=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - tzdata=2024b=hc8b5060_0
  - ucrt=10.0.22621.0=h57928b3_1
  - unicodedata2=15.1.0=py312h4389bb4_1
  - uriparser=0.9.8=h5a68840_0
  - urllib3=2.2.3=pyhd8ed1ab_1
  - vc=14.3=ha32ba9b_23
  - vc14_runtime=14.42.34433=he29a5d6_23
  - verde=1.8.1=pyhd8ed1ab_0
  - vs2015_runtime=14.42.34433=hdffcdeb_23
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - wrapt=1.17.0=py312h4389bb4_0
  - x265=3.5=h2d74725_3
  - xarray=2024.11.0=pyhd8ed1ab_0
  - xerces-c=3.2.5=he0c23c2_2
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xrft=1.0.1=pyhd8ed1ab_1
  - xyzservices=2024.9.0=pyhd8ed1ab_1
  - yaml=0.2.5=h8ffe710_2
  - yarl=1.18.3=py312h4389bb4_0
  - zarr=2.18.4=pyhd8ed1ab_0
  - zeromq=4.3.5=ha9f60a1_7
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=h2466b09_2
  - zstandard=0.23.0=py312h7606c53_1
  - zstd=1.5.6=h0ea2cb4_0
  - pip:
      - pyproj==3.7.0
prefix: C:\Users\mattd\miniforge3\envs\polartoolkit
