name: polartoolkit
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - accessible-pygments=0.0.5=pyhd8ed1ab_1
  - affine=2.4.0=pyhd8ed1ab_1
  - aiobotocore=2.25.0=pyhcf101f3_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.0=py312h033f2cf_0
  - aioitertools=0.12.0=pyhd8ed1ab_1
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alabaster=1.0.0=pyhd8ed1ab_1
  - anyio=4.11.0=pyhcf101f3_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py312h4c3975b_1
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.9.1=h48c9088_3
  - aws-c-cal=0.9.2=he7b75e1_1
  - aws-c-common=0.12.4=hb03c661_0
  - aws-c-compression=0.3.1=h92c474e_6
  - aws-c-event-stream=0.5.6=h82d11aa_3
  - aws-c-http=0.10.4=h94feff3_3
  - aws-c-io=0.22.0=h57f3b0d_1
  - aws-c-mqtt=0.13.3=h2b1cf8c_6
  - aws-c-s3=0.8.6=h4e5ac4b_5
  - aws-c-sdkutils=0.2.4=h92c474e_1
  - aws-checksums=0.2.7=h92c474e_2
  - aws-crt-cpp=0.34.4=h60c762c_0
  - aws-sdk-cpp=1.11.606=h32384e2_4
  - azure-core-cpp=1.16.0=h3a458e0_1
  - azure-identity-cpp=1.12.0=ha729027_0
  - azure-storage-blobs-cpp=12.14.0=hb1c9500_1
  - azure-storage-common-cpp=12.10.0=h4bb41a7_3
  - azure-storage-files-datalake-cpp=12.12.0=h8b27e44_3
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.14.2=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - blosc=1.21.6=he440d0b_1
  - bokeh=3.8.0=pyhd8ed1ab_0
  - botocore=1.40.49=pyhd8ed1ab_0
  - bounded-pool-executor=0.0.3=pyhd8ed1ab_0
  - branca=0.8.2=pyhd8ed1ab_0
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - brotli-python=1.1.0=py312h1289d80_4
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cartopy=0.25.0=py312hf79963d_1
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py312h35888ee_0
  - cftime=1.6.4=py312h4f23490_2
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - choclo=0.3.2=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - colorcet=3.1.0=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py312hd9148b4_2
  - coverage=7.10.7=py312h8a5da7c_0
  - cpython=3.12.12=py312hd8ed1ab_0
  - crc32c=2.7.1.post0=py312h5253ce2_0
  - curl=8.14.1=h332b0f4_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cytoolz=1.0.1=py312h66e93f0_0
  - dask=2025.9.1=pyhcf101f3_0
  - dask-core=2025.9.1=pyhcf101f3_0
  - datashader=0.18.2=pyhd8ed1ab_0
  - dcw-gmt=2.2.0=ha770c72_0
  - debugpy=1.8.17=py312h8285ef7_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - deepdiff=8.6.1=pyhcf101f3_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.18=pyhd8ed1ab_0
  - deprecation=2.1.0=pyh9f0ad1d_0
  - distributed=2025.9.1=pyhcf101f3_0
  - docrep=0.3.2=pyh44b312d_0
  - docutils=0.21.2=pyhd8ed1ab_1
  - donfig=0.8.1.post1=pyhd8ed1ab_1
  - earthaccess=0.15.1=pyhcf101f3_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fftw=3.3.10=nompi_hf1063bd_110
  - folium=0.20.0=pyhd8ed1ab_0
  - fonttools=4.60.1=py312h8a5da7c_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=ha770c72_0
  - freexl=2.0.0=h9dce30a_2
  - frozenlist=1.7.0=py312h447239a_0
  - fsspec=2025.9.0=pyhd8ed1ab_0
  - future=1.0.0=pyhd8ed1ab_2
  - geopandas=1.1.1=pyhd8ed1ab_1
  - geopandas-base=1.1.1=pyha770c72_1
  - geos=3.14.0=h480dda7_0
  - geotiff=1.7.4=h1000f5c_4
  - geoviews=1.14.1=hd8ed1ab_0
  - geoviews-core=1.14.1=pyha770c72_0
  - gflags=2.2.2=h5888daf_1005
  - ghostscript=10.06.0=hecca717_0
  - giflib=5.2.2=hd590300_0
  - glog=0.7.1=hbabe93e_0
  - gmt=6.6.0=h0d54b5c_4
  - gshhg-gmt=2.3.7=ha770c72_1003
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - h5netcdf=1.6.4=pyhd8ed1ab_0
  - h5py=3.14.0=nompi_py312ha4f8f14_101
  - harmonica=0.7.0=pyhd8ed1ab_1
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.6=nompi_h6e4c0c1_103
  - holoviews=1.21.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_1
  - ipykernel=7.0.0=pyha191276_0
  - ipyleaflet=0.20.0=pyhd8ed1ab_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jmespath=1.0.1=pyhd8ed1ab_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - json-c=0.18=h6688a6e_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py312h7900ff3_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_leaflet=0.20.0=pyhd8ed1ab_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.9=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py312h0a2e395_1
  - krb5=1.21.3=h659f571_0
  - lark=1.3.0=pyhd8ed1ab_0
  - latexcodec=2.0.1=pyh9f0ad1d_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250512.1=cxx17_hba17884_0
  - libaec=1.1.4=h3f801dc_0
  - libarchive=3.8.1=gpl_h7be2006_101
  - libarrow=21.0.0=h56a6dad_8_cpu
  - libarrow-acero=21.0.0=h635bf11_8_cpu
  - libarrow-compute=21.0.0=h8c2c5c3_8_cpu
  - libarrow-dataset=21.0.0=h635bf11_8_cpu
  - libarrow-substrait=21.0.0=h3f74fd7_8_cpu
  - libblas=3.9.0=37_h4a7cf45_openblas
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcblas=3.9.0=37_h0358290_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgdal-core=3.10.3=hdabd086_21
  - libgdal-jp2openjpeg=3.10.3=hdd07572_21
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libglib=2.86.0=h1fed272_0
  - libgomp=15.2.0=h767d61c_7
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgrpc=1.73.1=h1e535eb_0
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - libkml=1.3.0=hf539b9f_1021
  - liblapack=3.9.0=37_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libnetcdf=4.9.3=nompi_h11f7409_103
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libparquet=21.0.0=h790f06f_8_cpu
  - libpng=1.6.50=h421ea60_1
  - libprotobuf=6.31.1=h9ef548d_1
  - libre2-11=2025.08.12=h7b12aa8_1
  - librttopo=1.1.0=h96cd706_19
  - libsodium=1.0.20=h4ab18f5_0
  - libspatialite=5.1.0=gpl_hcb59c51_118
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.1=h8261f1e_0
  - libutf8proc=2.11.0=hb04c3b8_0
  - libuuid=2.41.2=he9a06e4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.0=h26afc86_1
  - libxml2-16=2.15.0=ha9997c6_1
  - libxml2-devel=2.15.0=h26afc86_1
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - linkify-it-py=2.0.3=pyhd8ed1ab_1
  - llvmlite=0.45.1=py312h7424e68_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.4=py312h5d89b6d_1
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=h280c20c_1002
  - mapclassify=2.10.0=pyhd8ed1ab_1
  - markdown=3.9=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.3=py312h8a5da7c_0
  - matplotlib-base=3.10.6=py312he3d6523_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdit-py-plugins=0.5.0=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - minizip=4.0.10=h05a5f5f_0
  - mistune=3.1.4=pyhcf101f3_0
  - msgpack-python=1.1.2=py312hd9148b4_0
  - multidict=6.6.3=py312h178313f_0
  - multimethod=2.0=pyhd8ed1ab_0
  - multipledispatch=0.6.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - myst-parser=4.0.1=pyhd8ed1ab_0
  - narwhals=2.8.0=pyhcf101f3_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert=7.16.6=hb482800_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbconvert-pandoc=7.16.6=hed9df3c_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nbsphinx=0.9.7=pyhd8ed1ab_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - netcdf4=1.7.2=nompi_py312hf6400b3_104
  - networkx=3.5=pyhe01879c_0
  - nlohmann_json=3.12.0=h54a6638_1
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numba=0.62.1=py312h907b442_0
  - numcodecs=0.16.1=py312hf79963d_2
  - numpy=2.3.3=py312h33ff503_0
  - openjpeg=2.5.4=h55fea9a_0
  - openpyxl=3.1.5=py312h7f6eeab_2
  - openssl=3.5.4=h26f9b46_0
  - orc=2.2.1=hd747db4_0
  - orderly-set=5.5.0=pyhe01879c_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py312hf79963d_1
  - pandoc=3.8.2=ha770c72_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - panel=1.8.2=pyhd8ed1ab_0
  - param=2.2.1=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.46=h1321c63_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py312h7b42cdd_3
  - pip=25.2=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_3
  - pqdm=0.2.0=pyhd8ed1ab_1
  - proj=9.7.0=hb72c0af_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py312h178313f_0
  - psutil=7.1.0=py312h4c3975b_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=21.0.0=py312h7900ff3_1
  - pyarrow-core=21.0.0=py312hc195796_1_cpu
  - pybtex=0.25.1=pyhd8ed1ab_0
  - pybtex-docutils=1.0.3=py312h7900ff3_3
  - pycparser=2.22=pyh29332c3_1
  - pyct=0.6.0=pyhd8ed1ab_0
  - pydata-sphinx-theme=0.15.4=pyhd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pygmt=0.17.0=pyhcf101f3_0
  - pyogrio=0.11.0=py312h02b19dd_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyproj=3.7.2=py312h9b6a7d9_2
  - pyshp=3.0.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=8.4.2=pyhd8ed1ab_0
  - pytest-cov=7.0.0=pyhcf101f3_1
  - python=3.12.12=hfe2f287_0_cpython
  - python-cmr=0.13.0=pyhff2d567_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.1.1=pyhe01879c_0
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.12.12=hd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyviz_comms=3.0.6=pyhd8ed1ab_0
  - pyyaml=6.0.3=py312h8a5da7c_0
  - pyzmq=27.1.0=py312hfb55c3c_0
  - qhull=2020.2=h434a139_5
  - rasterio=1.4.3=py312h762fea3_3
  - re2=2025.08.12=h5301d42_1
  - readline=8.2=h8c095d6_2
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rioxarray=0.19.0=pyhd8ed1ab_0
  - roman-numerals-py=3.1.0=pyhd8ed1ab_0
  - rpds-py=0.27.1=py312h868fb18_1
  - s2n=1.5.26=h5ac9029_0
  - s3fs=2025.9.0=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py312h4f0b9e3_0
  - scipy=1.16.2=py312h7a1785b_0
  - send2trash=1.8.3=pyh0d859eb_1
  - setuptools=80.9.0=pyhff2d567_0
  - shapely=2.1.2=py312h950be2a_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - snowballstemmer=3.0.1=pyhd8ed1ab_0
  - snuggs=1.4.7=pyhd8ed1ab_2
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - sphinx=8.2.3=pyhd8ed1ab_0
  - sphinx-autodoc-typehints=3.5.1=pyhd8ed1ab_0
  - sphinx-book-theme=1.1.4=pyh29332c3_0
  - sphinx-copybutton=0.5.2=pyhd8ed1ab_1
  - sphinx-design=0.6.1=pyhd8ed1ab_2
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-bibtex=2.6.5=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_1
  - sqlite=3.50.4=hbc0de68_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tblib=3.1.0=pyhd8ed1ab_0
  - tenacity=9.1.2=pyhd8ed1ab_0
  - terminado=0.18.1=pyh0d859eb_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tinynetrc=1.3.1=pyhd8ed1ab_0
  - tk=8.6.13=noxft_hd72426e_102
  - tomli=2.3.0=pyhcf101f3_0
  - toolz=1.0.0=pyhd8ed1ab_1
  - tornado=6.5.2=py312h4c3975b_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - traittypes=0.2.1=pyh9f0ad1d_2
  - types-python-dateutil=2.9.0.20251008=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - uc-micro-py=1.0.3=pyhd8ed1ab_1
  - unicodedata2=16.0.0=py312h4c3975b_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - uriparser=0.9.8=hac33072_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - verde=1.8.1=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - wrapt=1.17.3=py312h4c3975b_1
  - xarray=2025.10.1=pyhd8ed1ab_0
  - xerces-c=3.2.5=h988505b_2
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - yaml=0.2.5=h280c20c_3
  - yarl=1.20.1=py312h178313f_0
  - zarr=3.1.3=pyhcf101f3_0
  - zeromq=4.3.5=h387f397_9
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.25.0=py312h5253ce2_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - cattrs==25.3.0
      - lxml==6.0.2
      - polartoolkit==1.2.1.dev0+gc370922a1.d20251029
      - pydap==3.5.8
      - requests-cache==1.2.1
      - url-normalize==2.2.1
      - webob==1.8.9
      - xrft==1.0.1
prefix: /home/sungw937/miniforge3/envs/polartoolkit
