name: release

# define when this workflow is triggered
on:
  workflow_dispatch:
  release:
    types: [published]

# cancel any currently running workflows in this same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Always build & lint package. Need to re-checkout after semantic-release in case it
  # made a commit
  build-package:
    name: Build & verify package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: hynek/build-and-inspect-python-package@v1

  # Upload to Test PyPI.
  release-test-pypi:
    name: Publish in-dev package to test.pypi.org
    runs-on: ubuntu-latest
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    environment:
      name: testpypi
      url: https://pypi.org/p/antarctic-plots
    needs: [build-package]
    steps:
      # Download the build package files
      - name: Download packages built by build-and-inspect-python-package
        with:
          name: Packages
          path: dist
        uses: actions/download-artifact@v3

      - name: Upload package to Test PyPI
        with:
          repository-url: https://test.pypi.org/legacy/
        uses: pypa/gh-action-pypi-publish@release/v1

  # Upload to real PyPI on GitHub Releases.
  release-pypi:
    name: Publish released package to pypi.org
    runs-on: ubuntu-latest
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    environment:
      name: pypi
      url: https://pypi.org/p/antarctic-plots
    needs: [build-package]
    steps:
      # Download the build package files
      - name: Download packages built by build-and-inspect-python-package
        with:
          name: Packages
          path: dist
        uses: actions/download-artifact@v3

      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
